# Site settings
title: Alidoces
email: seuemail@alidoces.com
url:  http://alidocesoficial.github.io
baseurl: /
description: "Portfólio da Alidoces"
keywords: "Bolos, Doces, Alidoces"
meta_author: Alidoces


color:
  primary: ED5565 
  primary-rgb: "216, 51, 74, 0.75" 
  secondary: D8334A 
  secondary-dark: rgba(0, 0, 0, 0.09)


footer:
  copyright: Alidoces
  localizacao: Localização
  social: Redes Sociais
  creditos: Creditos


social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: instagram
    url: 


address:
  - line: Rua José Luís de Jesus, 52
  - line: Osasco - SP
  - line: Brasil


credits: 'Desenvolvido por <a href="http://andreyglauzer.com">Andrey Glauzer</a>, usando Jekyll.'


markdown: kramdown
permalink: pretty
